version: 2

models:
  - name: stg_hello
    description: "Modelo de validação inicial"
    columns:
      - name: msg
        tests:
          - not_null
      - name: ts
        tests:
          - not_null
